services:
  app:
    build: .
    ports:
      - "1401:8080"
    networks:
      - common-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environments:
      MYSQL_DATABASE: springboot
      MYSQL_USERNAME: root 
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - common-networks

  networks:
    common-network:
      external: true
    name: common-network
