services:
  app:
    build: .
    ports:
      - "1401:8080"
    networks:
      - common-network
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: FoodFrenzy
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - common-network

networks:
  common-network:
    external: true
    name: common-network
